# Generated by Django 3.1.7 on 2021-03-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='unread',
            field=models.BooleanField(default=True),
        ),
    ]
