# Generated by Django 3.1.7 on 2021-03-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_user', '0003_auto_20210301_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
