# Generated by Django 3.1.7 on 2021-03-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_user', '0004_auto_20210312_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
