# Generated by Django 3.1.7 on 2021-03-01 18:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_tweets', '0004_auto_20210301_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 18, 7, 4, 929866, tzinfo=utc)),
        ),
    ]
