# Generated by Django 3.1.7 on 2021-03-02 17:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_tweets', '0006_auto_20210301_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 17, 24, 24, 993896, tzinfo=utc)),
        ),
    ]
