# Generated by Django 3.1.7 on 2021-03-02 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_tweets', '0007_auto_20210302_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
